services:
  - type: web
    name: nova-lotto
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: postgresql://postgres:Myster44@db.fpekfulgjuycwzybiznt.supabase.co:5432/postgres
      - key: PORT
        value: 10000